(source "melpa" "http://melpa.org/packages/")
(source gnu)

(depends-on "cask")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "fiplr")
(depends-on "grizzl")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "s")
(depends-on "shut-up")
(depends-on "neotree")
