(source melpa)

(depends-on "ac-php")
(depends-on "ac-php-core")
(depends-on "auto-complete")
(depends-on "elixir-mode")
(depends-on "jsx-mode")
(depends-on "pallet")
(depends-on "php-mode")
(depends-on "rjsx-mode")
(depends-on "robe")
(depends-on "rubocop")
(depends-on "rust-mode")
